# Generated by Django 3.1.2 on 2022-03-27 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriber', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilesubscribermodel',
            name='customer_id_owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Customer_id_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mobilesubscribermodel',
            name='customer_id_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Customer_id_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
